-- Template storage for the schema-driven renderer + AI designer.
-- Run against the same database as MysqlCreateStatement.txt.

CREATE TABLE IF NOT EXISTS TEMPLATE_DETAILS (
    TEMPLATE_ID   INT AUTO_INCREMENT PRIMARY KEY,
    CLIENT_ID     VARCHAR(255) NOT NULL,
    TEMPLATE_NAME VARCHAR(100) NOT NULL,
    TEMPLATE_JSON JSON NOT NULL,
    CREATED_BY    VARCHAR(255),
    CREATED_ON    DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY    VARCHAR(255),
    UPDATED_ON    DATETIME,
    UNIQUE KEY uq_client_template (CLIENT_ID, TEMPLATE_NAME),
    CONSTRAINT fk_template_client FOREIGN KEY (CLIENT_ID)
        REFERENCES CLIENT_DETAILS (CLIENT_ID)
);
