-- Bulk pipeline: one row per uploaded roster / batch job.
-- STATUS: PENDING_REVIEW -> RENDERING -> DONE (or FAILED).
-- ROWS_JSON holds the mapped roster; ANOMALIES_JSON the maker-checker report;
-- ERRORS_JSON any per-row render failures.

CREATE TABLE IF NOT EXISTS BATCH_JOBS (
    JOB_ID         INT AUTO_INCREMENT PRIMARY KEY,
    CLIENT_ID      VARCHAR(255) NOT NULL,
    TEMPLATE_NAME  VARCHAR(100),
    NAME_FIELD     VARCHAR(100) NOT NULL DEFAULT 'RECIPIENT_NAME',
    STATUS         VARCHAR(20)  NOT NULL DEFAULT 'PENDING_REVIEW',
    TOTAL          INT NOT NULL DEFAULT 0,
    PROCESSED      INT NOT NULL DEFAULT 0,
    SUCCEEDED      INT NOT NULL DEFAULT 0,
    FAILED         INT NOT NULL DEFAULT 0,
    ROWS_JSON      JSON,
    ANOMALIES_JSON JSON,
    ERRORS_JSON    JSON,
    ZIP_PATH       LONGTEXT,
    CREATED_ON     DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_ON     DATETIME,
    KEY idx_batch_client (CLIENT_ID),
    CONSTRAINT fk_batch_client FOREIGN KEY (CLIENT_ID)
        REFERENCES CLIENT_DETAILS (CLIENT_ID)
);
